cargo-features = ["codegen-backend"]
[package]
name = "no-mouth"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "*", default-features = false, features = [
  "animation",
  "bevy_asset",
  "bevy_color",
  "bevy_core_pipeline",
  "bevy_gilrs",
  "bevy_gizmos",
  "bevy_gltf",
  "bevy_mesh_picking_backend",
  "bevy_pbr",
  "bevy_picking",
  "bevy_render",
  "bevy_scene",
  "bevy_sprite",
  "bevy_sprite_picking_backend",
  "bevy_state",
  "bevy_text",
  "bevy_ui",
  "bevy_ui_picking_backend",
  "bevy_window",
  "bevy_winit",
  "custom_cursor",
  "default_font",
  "hdr",
  "multi_threaded",
  "png",
  "smaa_luts",
  "sysinfo_plugin",
  "tonemapping_luts",
  "webgl2",
  "wayland",
	"file_watcher",
	"dynamic_linking"
] }
bevy_dylib = { version = "*" }
avian2d = "*"
bevy_framepace = "*"
bevy_seedling = "*"
dogoap = "*"
bevy_enhanced_input = "*"
bevy-inspector-egui = "*"
bevy_yarnspinner = "*"
bevy_yarnspinner_example_dialogue_view = "*"
iyes_perf_ui = "*"
bevy_ecs_ldtk = "*"
bevy_simple_subsecond_system = "*"

[profile.dev]
opt-level = 1 

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
incremental = false
debug = false

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
