cargo-features = ["codegen-backend"]
[package]
name = "no-mouth"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "*", features = [ "wayland", "dynamic_linking" ]}
bevy_dylib = { version = "*" }
avian2d = "*"
bevy_framepace = "*"
bevy_ecs_tiled = "*"
bevy_seedling = "*"
dogoap = "*"
bevy_yarnspinner = "*"
bevy_enhanced_input = "*"

[profile.dev]
opt-level = 1 

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
incremental = false
debug = false
